# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1529758880);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1529759000);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1529758520);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1529758760);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1529759240);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1529758640);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1529245187);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1529759120);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1529244319);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 59);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ec9b073e-c490-44d6-a355-1fbe08be456b}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1529173800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1529758494);
user_pref("browser.onboarding.notification.prompt-count", 5);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.open.lastDir", "/home/caret/Downloads");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1529758509925");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1529760329925");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1529758516069");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1529762116069");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180208175058");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1529758494");
user_pref("browser.slowStartup.averageTime", 13022);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20180208175058");
user_pref("browser.startup.homepage_override.mstone", "58.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":13,\"newElementCount\":2}");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1529244337813");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "58.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 23);
user_pref("extensions.getAddons.cache.lastUpdate", 1529244708);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180208175058");
user_pref("extensions.lastAppVersion", "58.0.2");
user_pref("extensions.lastPlatformVersion", "58.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.startupExperimentPrefs.browser.urlbar.matchBuckets", "suggestion:4,general:5");
user_pref("extensions.shield-recipe-client.user_id", "dbb23183-e3cc-4657-b16e-9143d3b30b98");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"093da41d-ad3f-4614-9ba1-aa779bc874fc\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1529244720);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180208175058");
user_pref("media.gmp-manager.lastCheck", 1529758539);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1529091706);
user_pref("services.blocklist.clock_skew_seconds", 153121);
user_pref("services.blocklist.gfx.checked", 1529091706);
user_pref("services.blocklist.last_etag", "\"1528408770328\"");
user_pref("services.blocklist.last_update_seconds", 1529091706);
user_pref("services.blocklist.onecrl.checked", 1529091706);
user_pref("services.blocklist.pinning.checked", 1529091706);
user_pref("services.blocklist.plugins.checked", 1529091706);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1529758486);
user_pref("toolkit.telemetry.cachedClientID", "345b6bd7-83c1-4f9e-b092-f3ff1e4f29a5");
user_pref("toolkit.telemetry.previousBuildID", "20180208175058");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
